theme: jekyll-theme-minimal
title: COMP4670/8600 Statistical Machine Learning
description: This is a broad but thorough intermediate level course of statistical machine learning, emphasising the mathematical, statistical, and computational aspects.


